module.exports = {
	"DESCRIPTION": {
		"adjectives": {
			"able"              : 1,
			"adaptable"         : 2,
			"adventurous"       : 3,
			"aggressive"        : 4,
			"ambitious"         : 5,
			"anxious"           : 6,
			"arrogant"          : 7,
			"artistic"          : 8,
			"attentive"         : 9,
			"authoritative"     : 10,
			"bold"              : 11,
			"brave"             : 12,
			"business"          : 13,
			"charming"          : 14,
			"cheerful"          : 15,
			"clever"            : 16,
			"compassionate"     : 17,
			"competitive"       : 18,
			"conscientious"     : 19,
			"confident"         : 20,
			"conservative"      : 21,
			"considerate"       : 22,
			"courageous"        : 23,
			"cynical"           : 24,
			"dependable"        : 25,
			"deep"              : 26,
			"diligent"          : 27,
			"disorganized"      : 28,
			"docile"            : 29,
			"earnest"           : 30,
			"empathetic"        : 31,
			"extrovert"         : 32,
			"exuberant"         : 33,
			"fair"              : 34,
			"focused"           : 35,
			"forgiving"         : 36,
			"generous"          : 37,
			"gentle"            : 38,
			"gracious"          : 39,
			"honest"            : 40,
			"hopeful"           : 41,
			"humble"            : 42,
			"humorous"          : 43,
			"idealistic"        : 44,
			"individual"        : 45,
			"industrious"       : 46,
			"innocent"          : 47,
			"innovative"        : 48,
			"insightful"        : 49,
			"inspirational"     : 50,
			"intelligent"       : 51,
			"intuitive"         : 52,
			"inventive"         : 53,
			"investigative"     : 54,
			"jealous"           : 55,
			"joyful"            : 56,
			"kind"              : 57,
			"knowledgeable"     : 58,
			"meticulous"        : 59,
			"modest"            : 60,
			"mysterious"        : 61,
			"naive"             : 62,
			"noble"             : 63,
			"open-minded"       : 64,
			"orderly"           : 65,
			"outspoken"         : 66,
			"passionate"        : 67,
			"perceptive"        : 68,
			"persistent"        : 69,
			"philosophical"     : 70,
			"practical"         : 71,
			"prideful"          : 72,
			"punctual"          : 73,
			"quick"             : 74,
			"quiet"             : 75,
			"quirky"            : 76,
			"rational"          : 77,
			"reasonable"        : 78,
			"reckless"          : 79,
			"refined"           : 80,
			"reliable"          : 81,
			"reserved"          : 82,
			"resilient"         : 83,
			"resourceful"       : 84,
			"respectful"        : 85,
			"responsible"       : 86,
			"selfish"           : 87,
			"sensible"          : 88,
			"sensitive"         : 89,
			"serious"           : 90,
			"shrewd"            : 91,
			"solemn"            : 92,
			"solitary"          : 93,
			"stern"             : 94,
			"studious"          : 95,
			"supportive"        : 96,
			"sweet"             : 97,
			"sympathetic"       : 98,
			"systematic"        : 99,
			"tactful"           : 100,
			"temperate"         : 101,
			"tenacious"         : 102,
			"thoughtful"        : 103,
			"tolerant"          : 104,
			"trustworthy"       : 105,
			"uplifting"         : 106,
			"valiant"           : 107,
			"vigilant"          : 108,
			"warm"              : 109,
			"wise"              : 110,
			"witty"             : 111,
			"youthful"          : 112
		},
		"nouns": {
			

		},
		"verbs": {

		},
		"adverbs": {

		},
		"articles": {
			"a"     : 1,
			"an"    : 2,
			"the"   : 3
		}
	}
}